language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem update --system
install:
  - npm install
  - npm install -g bower grunt-cli

before_script:
  - cd log4js
  - npm install
script:
  - grunt --gruntfile "Gruntfile.js" build --verbose
